config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :trades
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'trades#index'

  get "/trades", to: "trades#index"
  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :trades
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :category

  validates :product, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category_name)
    end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: %i[ show edit update destroy ]

  # GET /trades or /trades.json
  def index
    @trades = Trade.all
  end

  # GET /trades/1 or /trades/1.json
  #create trade and category_name instance variables and assign each a category attribute
  def show
    @trade = Trade.find(params[:id])
    @category_name = @trade.category.category_name
  end

  # GET /trades/new returns a new trade
  def new
    @trade = Trade.new
    @categories = Category.all
  end

  # GET /trades/1/edit
  def edit
    @trade = Trade.find(params[:id])
    @categories = Category.all
  end

  # POST /trades or /trades.json return the trade object and save it to the database
  def create
    @trade = Trade.new(trade_params)

    respond_to do |format|
      if @trade.save
        format.html { redirect_to trade_url(@trade), notice: "Trade was successfully created." }
        format.json { render :show, status: :created, location: @trade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1 or /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        format.html { redirect_to trade_url(@trade), notice: "Trade was successfully updated." }
        format.json { render :show, status: :ok, location: @trade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1 or /trades/1.json
  def destroy
    @trade.destroy

    respond_to do |format|
      format.html { redirect_to trades_url, notice: "Trade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade
      @trade = Trade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trade_params
      params.require(:trade).permit(:product, :description, :category_name, :category_id, :expiration, :neighborhood, :user_id, :interested_in, :accept, :image_file_name, :image_content_type, :image_updated_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Category name:</strong>
    <%= category.category_name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category_name, style: "display: block" %>
    <%= form.text_field :category_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tradenpost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trades/_form.html.erb
<%= form_with(model: trade) do |form| %>
  <% if trade.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
        <% trade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product, style: "display: block" %>
    <%= form.text_field :product %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

<!-- choose what category your produce should be in,-->
<!-- :trade and :category_name look for the instance variables called @trade/ @cateogry_name in trades_controller -->
<!-- @categories assigns the category selected to the new trade item -->
  <div>
    <%= form.label :category, style: "display: block" %>
    <%= collection_select(:trade, :category_id, @categories, :id, :category_name, {:prompt => true}) %>
  </div>

  <div>
    <%= form.label :neighborhood, style: "display: block" %>
    <%= form.text_field :neighborhood %>
  </div>

  <div>
    <%= form.label :expiration, style: "display: block" %>
    <%= form.date_field :expiration %>
  </div>

<!--
  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :interested_in, style: "display: block" %>
    <%= form.text_area :interested_in %>
  </div>

  <div>
    <%= form.label :accept, style: "display: block" %>
    <%= form.check_box :accept %>
  </div>

  <div>
    <%= form.label :image_file_name, style: "display: block" %>
    <%= form.text_field :image_file_name %>
  </div>

  <div>
    <%= form.label :image_content_type, style: "display: block" %>
    <%= form.text_field :image_content_type %>
  </div>

  <div>
    <%= form.label :image_updated_at, style: "display: block" %>
    <%= form.datetime_field :image_updated_at %>
  </div>
-->
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trades/_trade.html.erb
<div id="<%= dom_id trade %>">
  <p>
    <strong>Product:</strong>
    <%= trade.product %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= trade.description %>
  </p>
<!-- Show the category that was selected in the trade html form for the item trade -->
  <p>
    <strong>Category:</strong>
    <%= trade.category.category_name %>
  </p>

  <p>
    <strong>Expiration:</strong>
    <%= trade.expiration %>
  </p>

  <p>
    <strong>Neighborhood:</strong>
    <%= trade.neighborhood %>
  </p>

  <p>
    <strong>User:</strong>
    <%= trade.user_id %>
  </p>

  <p>
    <strong>Interested in:</strong>
    <%= trade.interested_in %>
  </p>

  <p>
    <strong>Accept:</strong>
    <%= trade.accept %>
  </p>

  <p>
    <strong>Image file name:</strong>
    <%= trade.image_file_name %>
  </p>

  <p>
    <strong>Image content type:</strong>
    <%= trade.image_content_type %>
  </p>

  <p>
    <strong>Image updated at:</strong>
    <%= trade.image_updated_at %>
  </p>

</div>

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render "form", trade: @trade %>

<br>

<div>
  <%= link_to "Show this trade", @trade %> |
  <%= link_to "Back to trades", trades_path %>
</div>

app/views/trades/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trades</h1>

<div id="trades">
  <% @trades.each do |trade| %>
    <%= render trade %>
    <p>
      <%= link_to "Show this trade", trade %>
    </p>
  <% end %>
</div>

<%= link_to "New trade", new_trade_path %>

app/views/trades/new.html.erb
<h1>New trade</h1>

<%= render "form", trade: @trade %>

<br>

<div>
  <%= link_to "Back to trades", trades_path %>
</div>

app/views/trades/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trade %>

<div>
  <%= link_to "Edit this trade", edit_trade_path(@trade) %> |
  <%= link_to "Back to trades", trades_path %>

  <%= button_to "Destroy this trade", @trade, method: :delete %>
</div>